### ISSUE TITLE
Could not compile with newest github.com/prometheus/client_golang/prometheus

### ISSUE THREAD

**Issue by laodouya** [jaegertracing/jaeger-lib#33]
`# github.com/uber/jaeger-lib/metrics/prometheus
../../../github.com/uber/jaeger-lib/metrics/prometheus/factory.go:143:12: cannot use hv.WithLabelValues(f.tagsAsLabelValues(labelNames, tags)...) (type prometheus.Observer) as type prometheus.Histogram in field value:
	prometheus.Observer does not implement prometheus.Histogram (missing Collect method)
`

**Comment by laodouya** [comment]
It seems this project still use 0.8.0(a year and four months ago) version of github.com/prometheus/client_golang/prometheus

**Comment by black-adder** [comment]
This repo depends on https://github.com/uber-go/tally which has pinned the older version of prometheus. Once https://github.com/uber-go/tally/issues/42 is resolved, we can go ahead and support newer versions of prometheus, however we'd still somehow have to maintain backwards compatibility.

**Comment by yurishkuro** [comment]
0.8.0 is the latest official release (https://github.com/prometheus/client_golang/releases), so I don't see a problem here.

**Comment by painhardcore** [comment]
Same here:
```# test/vendor/github.com/uber/jaeger-lib/metrics/prometheus
vendor/github.com/uber/jaeger-lib/metrics/prometheus/factory.go:143:12: cannot use hv.WithLabelValues(f.tagsAsLabelValues(labelNames, tags)...) (type prometheus.Observer) as type prometheus.Histogram in field value:
        prometheus.Observer does not implement prometheus.Histogram (missing Collect method)
```
I'm using 
[[constraint]]
  branch = "master"
  name = "github.com/prometheus/client_golang"

**Comment by nickjackson** [comment]
@beorn7 mentions over [here](https://github.com/prometheus/client_golang/issues/375#issuecomment-364107923) that they "aim to keep tip of master branch always stable" as appose to relying on tags while its still pre v1.

I guess this is just one of those awkward stages where different people (rightly) have differing ideas about how and when to release software.

**Comment by beorn7** [comment]
More explanation about the tagging/releasing/stable state of prometheus/client_golang has been added to the README.md here: https://github.com/prometheus/client_golang#important-note-about-releases-versioning-tagging-stability-and-your-favorite-go-dependency-management-tool

**Comment by pavelnikolov** [comment]
#42 solved this

**Comment by yurishkuro** [comment]
Thanks @pavelnikolov
