### ISSUE TITLE
Define 2.0 release

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-lib#47]
There is a pending breaking change (#46). I suggest we take this opportunity to clean up the lib further. Specifically:

* [x] remove `metric/go-kit/prometheus` package, since we have `metrics/prometheus` implemented directly.
* [x] move LocalBackend to its own package. Maybe it should be explicitly in testutils, since the functions there already depend on the LocalBackend. Perhaps a better name is `metricstest`. (#46) (#51)
* [ ] require descriptions for metrics (#60)

**Comment by pohly** [comment]
Sounds good to me, there's just one small caveat: when and who? ;-}

Shall I do anything about PR #46 or close it?

**Comment by yurishkuro** [comment]
@pohly I am leaning towards not touching the import path renaming (item 1) at this time, as it seems to cause a lot of churn even at Uber internally. So if you change your PR to move everything related to the local backend into `metricstest` package, we can merge it. Item 2 is a simple delete, then we can release.

**Comment by isaachier** [comment]
Any update?

**Comment by yurishkuro** [comment]
We may want to consider #62 (Histograms) since it's a large breaking change

**Comment by objectiser** [comment]
@yurishkuro Assuming Jaeger 1.9 is going to be released this week, and that the recent changes to this lib (metrics factory API) are impacting some users, wondering whether #62 should be pushed to after 2.0 release?

Instead of it being a breaking change, it could be added alongside the `Timer` so minimise the impact on existing clients - and then maybe deprecated at a later stage if appropriate?

If agree, then ideally this lib should be released asap, to allow jaeger-client-go (update/release) followed by jaeger to be updated.

**Comment by yurishkuro** [comment]
We need to start an issue in the main repo about 1.9, I'm not clear what's included there. The grpc stuff has an unresolved issue with retries.

What is the dependency of 1.9 on jaeger-lib upgrade? Do we need to couple them?

The histogram is a breaking change since it extends the interface.

**Comment by objectiser** [comment]
The main benefit of getting jaeger-lib 2 into 1.9 would be sorting out the prometheus metric names - but it is not critical if we could do a 1.10 soon after jaeger-lib is released.

The main problem with jaeger-lib 2 is it seems to be causing jaeger-client-go users build issues. So was hoping to get this lib released, followed by go client and then use both in jaeger 1.9.

I'm taking a stab at #62 - hopefully will have something later today, but depends how long will take to iterate over.

**Comment by objectiser** [comment]
@yurishkuro Can version 2 be released as I think all items have been done, and it is impacting users: https://github.com/jaegertracing/jaeger-client-go/issues/352#issuecomment-447734606 ?
