### ISSUE TITLE
Bump the version of go-kit/kit to 0.9.0?

### ISSUE THREAD

**Issue by mijia** [jaegertracing/jaeger-lib#73]
## Requirement - what kind of business use case are you trying to solve?
Trying to add the jaeger-lib into my project, but it locks the version of go-kit/kit to 0.5.0 in dep 'Gopkg.toml', since we also need the influxstatsd version inside the go-kit/kit which only exists above the version of 0.5.0.
So far cannot dep add the jaeger-lib into the project.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Is that ok just bump the version of go-kit/kit to current 0.9.0? Would the apis be broken?

Thank you very much.

**Comment by yurishkuro** [comment]
we won't know until someone tries.

**Comment by vprithvi** [comment]
Done in #78
