### ISSUE TITLE
Define default buckets for Prometheus Histogram

### ISSUE THREAD

**Issue by moraitisk** [jaegertracing/jaeger-lib#89]
## Requirement - what kind of business use case are you trying to solve?

By default, the underlying prometheus client uses the following default buckets: 
```go
DefBuckets = []float64{.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10}
```
These values are tailored for measuring network latency, but also assume relatively low response times.

It should be possible to specify custom default buckets for the Histogram metric type that fit various use cases.

## Problem - what in Jaeger blocks you from solving the requirement?

A function `WithBuckets(buckets []float64)` is already exposed in the `prometheus` package to define default buckets for the `Factory` type. 

However, when calling the factory's `Histogram(options metrics.HistogramOptions)` method to build a new histogram, the default buckets that may have been set earlier are not taken into consideration. 

Instead, only the buckets from the provided `options` argument are used.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

The factory `Histogram` method should determine whether to use the configured default buckets or the buckets from the provided histogram options. If the `options.buckets` slice is nil, the defaults must be used.

## Any open questions to address

Please, let me know if all of this makes sense to you or have any additional questions. 

I have also addressed the necessary changes in the code and I'm ready to open a PR if you agree.

**Comment by yurishkuro** [comment]
Yes, looks like a bug in the implementation
